import Image from 'next/image'
import { Header } from './luxury-pages'

const yachts = {
  'sunseeker-74': {
    title: 'SUNSEEKER 74 SPORTS YACHT',
    hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-GZbMVb8PeoG7OgZ9TTi1r7cXEt1Bzv.png',
    side: ['https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=700&q=85'],
    description: 'The cues are all there. The low profile, the sleek yet elegant flowing lines, and beautiful craftsmanship complement cutting-edge technology and sophisticated interior finishes. The perfect yacht for socialising with guests, the 74 Sport Yacht has ample entertaining space, comfortable seating and generous storage for unforgettable days on the water.',
    specs: [['Manufacturer', 'Sunseeker'], ['Model', '65 Sport Yacht'], ['Built', '2023'], ['LOA (ft/m)', '67.2 / 20.48'], ['Beam (ft/m)', '16.8 / 5.12'], ['Draft (ft/m)', '16.8 / 5.12'], ['Displacement (kg)', '37810'], ['Propulsion', 'PODS'], ['Engine', 'TWIN VOLVO IPS 1200 (2 X 900PS), TWIN VOLVO IPS 1350 (2 X 1000PS)'], ['Generator', '13.5 KW @ 50HZ – 13.5 KW @ 60HZ'], ['Fuel Capacity (litres/us gal)', '800 / 211.34'], ['Full Speed (knots)', '35'], ['Cruise Speed (knots)', '10'], ['Crew Cabins', '1']],
  },
  'sunseeker-65': {
    title: 'SUNSEEKER 65 SPORT YACHT',
    hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-tXmoBKNhKqHG02A8Fz0eulhg8ciPr8.png',
    side: ['https://images.unsplash.com/photo-1605281317010-fe5ffe798166?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1566847438217-76e82d383f84?auto=format&fit=crop&w=700&q=85'],
    description: 'The all-new multi-award winning 65 Sport Yacht joins an expanding range of next-generation yachts. With an open-plan layout, generous entertaining areas and seamless access to the water, every detail has been designed for effortless cruising and memorable adventures.',
    specs: [['Manufacturer', 'Sunseeker'], ['Model', '65 Sport Yacht'], ['Built', '2023'], ['LOA (ft/m)', '67.2 / 20.48'], ['Beam (ft/m)', '16.8 / 5.12'], ['Draft (ft/m)', '16.8 / 5.12'], ['Displacement (kg)', '37810'], ['Propulsion', 'PODS'], ['Engine', 'TWIN VOLVO IPS 1200 (2 X 900PS), TWIN VOLVO IPS 1350 (2 X 1000PS)'], ['Generator', '13.5 KW @ 50HZ – 13.5 KW @ 60HZ'], ['Fuel Capacity (litres/us gal)', '800 / 211.34'], ['Full Speed (knots)', '35'], ['Cruise Speed (knots)', '10'], ['Crew Cabins', '1']],
  },
  'sunseeker-manhattan-68': {
    title: 'SUNSEEKER MANHATTAN 68', hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-1TTizjLf6MBBfFexkrh7BCk8TlH4xO.png', side: ['https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1540946485063-a40da27545f8?auto=format&fit=crop&w=700&q=85'], description: 'Built upon an exceptional family of award-winning Manhattan models, the Manhattan 68 offers an extraordinary level of comfort and luxury. Generous social spaces, an expansive main salon and beautifully considered interiors make this yacht ideal for long weekends and extended cruising.', specs: [['Manufacturer', 'Sunseeker'], ['Model', 'Manhattan 68'], ['Built', '2023'], ['LOA (ft/m)', '67.7 / 20.63'], ['Beam (ft/m)', '17.3 / 5.27'], ['Draft (ft/m)', '5.4 / 1.65'], ['Displacement (kg)', '374002'], ['Propulsion', 'PODS'], ['Engine', 'TWIN MAN V8 1000 (2 X 1000PS), TWIN VOLVO IPS'], ['Generator', '17.5KW@50HZ – 21.5KW@50HZ'], ['Full Speed (knots)', '32'], ['Cruise Speed (knots)', '10'], ['Crew Cabins', '2']],
  },
  'sunseeker-100': {
    title: '2023 SUNSEEKER 100', hero: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/image-HXRcVG00HuyqxHVGmsMlbn6YDYOeTZ.png', side: ['https://images.unsplash.com/photo-1605281317010-fe5ffe798166?auto=format&fit=crop&w=700&q=85', 'https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?auto=format&fit=crop&w=700&q=85'], description: 'The Sunseeker 100 Yacht is set to surprise and delight at every turn. Elegant, powerful lines flow around sublime architecture. A secluded private terrace, sunbathing hideaways, and generous open-plan interiors create an exceptional experience at sea.', specs: [['Manufacturer', 'Sunseeker'], ['Model', '100'], ['Built', '2023'], ['LOA (ft/m)', '97.1 / 29.6'], ['Beam (ft/m)', '22.8 / 6.95'], ['Draft (ft/m)', '6.1 / 1.86'], ['Displacement (kg)', '94119'], ['Propulsion', 'Shafts'], ['Engine', 'TWIN MTU 12V 2000 M96L SHAFT'], ['Generator', '2 x 35KW@50HZ'], ['Full Speed (knots)', '28'], ['Cruise Speed (knots)', '12'], ['Crew Cabins', '5']],
  },
} as const

export type Yacht = (typeof yachts)[keyof typeof yachts]
function Enquiry() { return <section className="bg-[#f8f7f4] px-6 py-24 sm:px-12 lg:px-20"><div className="mx-auto max-w-6xl"><p className="text-[10px] uppercase tracking-[0.3em] text-[#a8865c]">Find out more about luxury yachts</p><h2 className="mt-3 text-3xl font-semibold">Enquire About the Yachts</h2><h3 className="mt-5 text-2xl">Request a call back</h3><form className="mt-6 grid gap-4 sm:grid-cols-2"><input required aria-label="Name" placeholder="Name" className="h-12 rounded border border-[#e5e2dc] bg-white px-4 text-sm" /><input required aria-label="Last Name" placeholder="Last Name" className="h-12 rounded border border-[#e5e2dc] bg-white px-4 text-sm" /><input required type="email" aria-label="Email" placeholder="Email" className="h-12 rounded border border-[#e5e2dc] bg-white px-4 text-sm" /><input aria-label="Telephone" placeholder="Telephone" className="h-12 rounded border border-[#e5e2dc] bg-white px-4 text-sm" /><textarea required aria-label="Message" placeholder="Message" className="min-h-32 rounded border border-[#e5e2dc] bg-white px-4 py-3 text-sm sm:col-span-2" /><input required aria-label="Human check" placeholder="Are you human? 3 + 1 =" className="h-12 rounded border border-[#e5e2dc] bg-white px-4 text-sm" /><div className="sm:col-span-2"><button className="rounded-full border border-[#192327] px-6 py-3 text-xs">Submit</button></div></form></div></section> }
export function YachtDetailPage({ yacht }: { yacht: Yacht }) { return <main className="bg-white text-[#192327]"><section className="relative pt-20"><Header /><div className="mx-auto grid max-w-[1400px] grid-cols-12 items-center gap-5 overflow-hidden"><div className="col-span-2 hidden h-64 opacity-60 md:block"><Image src={yacht.side[0]} alt="Yacht detail" width={400} height={300} className="h-full w-full object-cover" /></div><div className="col-span-12 h-72 sm:h-[390px] md:col-span-8"><Image src={yacht.hero} alt={yacht.title} width={1200} height={700} className="h-full w-full object-cover" priority /></div><div className="col-span-2 hidden h-64 opacity-60 md:block"><Image src={yacht.side[1]} alt="Yacht detail" width={400} height={300} className="h-full w-full object-cover" /></div></div><div className="flex justify-center py-8"><button className="rounded-full border border-[#192327] px-6 py-2 text-xs">Fullscreen Gallery</button></div></section><section className="mx-auto max-w-6xl px-6 pb-24 sm:px-12"><h1 className="text-2xl font-semibold sm:text-3xl">{yacht.title}</h1><p className="mt-5 max-w-5xl text-sm leading-7 text-[#526064]">{yacht.description}</p><div className="mt-12 overflow-x-auto border border-[#ddd9d1]"><table className="w-full min-w-[650px] border-collapse text-xs"><tbody>{yacht.specs.map(([label, value]) => <tr key={label} className="border-b border-[#e5e2dc] last:border-0"><td className="w-1/3 border-r border-[#e5e2dc] px-3 py-2 text-[#526064]">{label}</td><td className="px-3 py-2 text-[#526064]">{value}</td></tr>)}</tbody></table></div></section><Enquiry /></main> }
export function getYacht(slug: string) { return yachts[slug as keyof typeof yachts] }
export const yachtSlugs = Object.keys(yachts)
